package de.benpicco.libchan.imageboards;

public enum Tags {
	NULL, POST, POST_ID, POST_USER, POST_TRIP, POST_TITLE, POST_THUMBNAIL, POST_IMGURL, POST_FILENAME, POST_COUNTRY, POST_DATE, POST_MESSAGE, POST_MAX_FILES, BOARD, BOARD_URL, BOARD_TITLE, BOARD_INDEX, SITE_NAME, SITE_DESC, SITE_URL, POST_THREAD, POST_THREAD_MARK, START_POST, END_POST, END_IMAGE, THUMBNAIL_PREFIX, IMAGE_PREFIX, COUNTRY_PREFIX, URL_PREFIX, URL_POSTFIX, INCLUDE, PARAM_NAME, PARAM_MAIL, PARAM_TITLE, PARAM_MESSAGE, PARAM_FILE, PARAM_CAPTCHA_ID, PARAM_CAPTCHA_SOLUTION, PARAM_BOARD, PARAM_REPLYTO, NEW_POST_URL
}
