package de.benpicco.libchan.imageboards;

public enum Tags {
	POST_ID, POST_USER, POST_TITLE, POST_THUMBNAIL, POST_IMGURL, POST_FILENAME, POST_COUNTRY, POST_DATE, POST_MESSAGE, BOARD_URL, POST_THREAD, START_POST, END_POST, END_IMAGE, THUMBNAIL_PREFIX, IMAGE_PREFIX, COUNTRY_PREFIX
}
